package com.example.demo;

import org.springframework.http.HttpHeaders;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

import java.net.URI;
import java.util.List;

// REST Controller for managing employees
@RestController
@RequestMapping("/employees")
public class EmployeeController {

    private final EmployeeDAO employeeDao;

    public EmployeeController(EmployeeDAO employeeDao) {
        this.employeeDao = employeeDao;
    }

    // GET endpoint to fetch all employees (JSON)
    @GetMapping("/")
    public List<Employee> getEmployees() {
        return employeeDao.getAllEmployees();
    }

    // Simple HTML page listing all employees
    @GetMapping("/page")
    public ResponseEntity<String> getEmployeesPage() {
        List<Employee> employees = employeeDao.getAllEmployees();

        StringBuilder html = new StringBuilder();
        html.append("<!DOCTYPE html>")
                .append("<html><head><title>Employees</title></head><body>")
                .append("<h1>Employees</h1>")
                .append("<ul>");

        for (Employee employee : employees) {
            html.append("<li>")
                    .append(employee.getId())
                    .append(" - ")
                    .append(employee.getName())
                    .append(" (")
                    .append(employee.getRole())
                    .append(")")
                    .append("</li>");
        }

        html.append("</ul></body></html>");

        return ResponseEntity
                .ok()
                .header(HttpHeaders.CONTENT_TYPE, "text/html; charset=UTF-8")
                .body(html.toString());
    }

    // POST endpoint to add a new employee
    @PostMapping("/")
    public ResponseEntity<Object> addEmployee(@RequestBody Employee employee) {

        // Persist employee in the database (ID will be generated by the DB)
        Employee saved = employeeDao.addEmployee(employee);

        // Build location URI for the new employee
        URI location = ServletUriComponentsBuilder
                .fromCurrentRequest()
                .path("/{id}")
                .buildAndExpand(saved.getId())
                .toUri();

        return ResponseEntity.created(location).build();
    }

    // DELETE endpoint to delete an employee
    @DeleteMapping("/{id}")
    public ResponseEntity<Object> deleteEmployee(@PathVariable Integer id) {
        employeeDao.deleteEmployee(id);
        return ResponseEntity.noContent().build();
    }
}
