package com.example.demo;

import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

import java.net.URI;
import java.time.LocalDate;
import java.util.List;

// Controller for managing employees
@Controller
@RequestMapping("/employees")
public class EmployeeController {

    private final EmployeeDAO employeeDao;

    public EmployeeController(EmployeeDAO employeeDao) {
        this.employeeDao = employeeDao;
    }

    // GET endpoint to fetch all employees (JSON)
    @GetMapping(value = {"", "/"}, produces = "application/json")
    @ResponseBody
    public List<Employee> getEmployees() {
        return employeeDao.getAllEmployees();
    }

    // Thymeleaf UI page for listing and managing employees
    @GetMapping({"/page", "/ui"})
    public String getEmployeesPage(Model model) {
        model.addAttribute("employees", employeeDao.getAllEmployees());
        return "employees";
    }

    // UI action: add employee via HTML form
    @PostMapping("/ui/add")
    public String addEmployeeFromForm(
            @RequestParam String name,
            @RequestParam String role,
            @RequestParam(required = false) String dob,
            @RequestParam(required = false) String email,
            @RequestParam(required = false) String department
    ) {
        LocalDate parsedDob = (dob == null || dob.isBlank()) ? null : LocalDate.parse(dob);
        employeeDao.addEmployee(new Employee(null, name, role, parsedDob, blankToNull(email), blankToNull(department)));
        return "redirect:/employees/ui";
    }

    @GetMapping("/ui/add")
    public String addEmployeeFromFormGet() {
        return "redirect:/employees/ui";
    }

    // UI action: update employee via HTML form
    @PostMapping("/ui/update")
    public String updateEmployeeFromForm(
            @RequestParam Integer id,
            @RequestParam String name,
            @RequestParam String role,
            @RequestParam(required = false) String dob,
            @RequestParam(required = false) String email,
            @RequestParam(required = false) String department
    ) {
        LocalDate parsedDob = (dob == null || dob.isBlank()) ? null : LocalDate.parse(dob);
        employeeDao.updateEmployee(id, new Employee(id, name, role, parsedDob, blankToNull(email), blankToNull(department)));
        return "redirect:/employees/ui";
    }

    @GetMapping("/ui/update")
    public String updateEmployeeFromFormGet() {
        return "redirect:/employees/ui";
    }

    // UI action: delete employee via HTML form
    @PostMapping("/ui/delete")
    public String deleteEmployeeFromForm(@RequestParam Integer id) {
        employeeDao.deleteEmployee(id);
        return "redirect:/employees/ui";
    }

    @GetMapping("/ui/delete")
    public String deleteEmployeeFromFormGet() {
        return "redirect:/employees/ui";
    }

    // POST endpoint to add a new employee (JSON)
    @PostMapping(value = {"", "/"}, consumes = "application/json")
    @ResponseBody
    public ResponseEntity<Object> addEmployee(@RequestBody Employee employee) {

        // Persist employee in the database (ID will be generated by the DB)
        Employee saved = employeeDao.addEmployee(employee);

        // Build location URI for the new employee
        URI location = ServletUriComponentsBuilder
                .fromCurrentRequest()
                .path("/{id}")
                .buildAndExpand(saved.getId())
                .toUri();

        return ResponseEntity.created(location).build();
    }

    // PUT endpoint to update an existing employee
    @PutMapping(value = "/{id}", consumes = "application/json")
    @ResponseBody
    public ResponseEntity<Object> updateEmployee(@PathVariable Integer id, @RequestBody Employee employee) {
        int rowsUpdated = employeeDao.updateEmployee(id, employee);
        if (rowsUpdated == 0) {
            return ResponseEntity.notFound().build();
        }
        return ResponseEntity.noContent().build();
    }

    // DELETE endpoint to delete an employee
    @DeleteMapping("/{id}")
    @ResponseBody
    public ResponseEntity<Object> deleteEmployee(@PathVariable Integer id) {
        employeeDao.deleteEmployee(id);
        return ResponseEntity.noContent().build();
    }

    private static String blankToNull(String value) {
        return (value == null || value.isBlank()) ? null : value.trim();
    }
}
